
import { Country } from '../types';

export const COUNTRIES: Country[] = [
  { name: 'United States', dial_code: '+1', code: 'US' },
  { name: 'United Kingdom', dial_code: '+44', code: 'GB' },
  { name: 'Afghanistan', dial_code: '+93', code: 'AF' },
  { name: 'Albania', dial_code: '+355', code: 'AL' },
  { name: 'Algeria', dial_code: '+213', code: 'DZ' },
  { name: 'American Samoa', dial_code: '+1684', code: 'AS' },
  { name: 'Andorra', dial_code: '+376', code: 'AD' },
  { name: 'Angola', dial_code: '+244', code: 'AO' },
  { name: 'Argentina', dial_code: '+54', code: 'AR' },
  { name: 'Armenia', dial_code: '+374', code: 'AM' },
  { name: 'Australia', dial_code: '+61', code: 'AU' },
  { name: 'Austria', dial_code: '+43', code: 'AT' },
  { name: 'Azerbaijan', dial_code: '+994', code: 'AZ' },
  { name: 'Bahrain', dial_code: '+973', code: 'BH' },
  { name: 'Bangladesh', dial_code: '+880', code: 'BD' },
  { name: 'Belarus', dial_code: '+375', code: 'BY' },
  { name: 'Belgium', dial_code: '+32', code: 'BE' },
  { name: 'Brazil', dial_code: '+55', code: 'BR' },
  { name: 'Canada', dial_code: '+1', code: 'CA' },
  { name: 'China', dial_code: '+86', code: 'CN' },
  { name: 'Egypt', dial_code: '+20', code: 'EG' },
  { name: 'France', dial_code: '+33', code: 'FR' },
  { name: 'Germany', dial_code: '+49', code: 'DE' },
  { name: 'India', dial_code: '+91', code: 'IN' },
  { name: 'Indonesia', dial_code: '+62', code: 'ID' },
  { name: 'Iran', dial_code: '+98', code: 'IR' },
  { name: 'Iraq', dial_code: '+964', code: 'IQ' },
  { name: 'Ireland', dial_code: '+353', code: 'IE' },
  { name: 'Italy', dial_code: '+39', code: 'IT' },
  { name: 'Japan', dial_code: '+81', code: 'JP' },
  { name: 'Jordan', dial_code: '+962', code: 'JO' },
  { name: 'Kuwait', dial_code: '+965', code: 'KW' },
  { name: 'Lebanon', dial_code: '+961', code: 'LB' },
  { name: 'Libya', dial_code: '+218', code: 'LY' },
  { name: 'Malaysia', dial_code: '+60', code: 'MY' },
  { name: 'Mexico', dial_code: '+52', code: 'MX' },
  { name: 'Morocco', dial_code: '+212', code: 'MA' },
  { name: 'Netherlands', dial_code: '+31', code: 'NL' },
  { name: 'New Zealand', dial_code: '+64', code: 'NZ' },
  { name: 'Nigeria', dial_code: '+234', code: 'NG' },
  { name: 'Oman', dial_code: '+968', code: 'OM' },
  { name: 'Pakistan', dial_code: '+92', code: 'PK' },
  { name: 'Palestine', dial_code: '+970', code: 'PS' },
  { name: 'Philippines', dial_code: '+63', code: 'PH' },
  { name: 'Poland', dial_code: '+48', code: 'PL' },
  { name: 'Portugal', dial_code: '+351', code: 'PT' },
  { name: 'Qatar', dial_code: '+974', code: 'QA' },
  { name: 'Russia', dial_code: '+7', code: 'RU' },
  { name: 'Saudi Arabia', dial_code: '+966', code: 'SA' },
  { name: 'South Africa', dial_code: '+27', code: 'ZA' },
  { name: 'South Korea', dial_code: '+82', code: 'KR' },
  { name: 'Spain', dial_code: '+34', code: 'ES' },
  { name: 'Sudan', dial_code: '+249', code: 'SD' },
  { name: 'Sweden', dial_code: '+46', code: 'SE' },
  { name: 'Switzerland', dial_code: '+41', code: 'CH' },
  { name: 'Syria', dial_code: '+963', code: 'SY' },
  { name: 'Tunisia', dial_code: '+216', code: 'TN' },
  { name: 'Turkey', dial_code: '+90', code: 'TR' },
  { name: 'United Arab Emirates', dial_code: '+971', code: 'AE' },
  { name: 'Yemen', dial_code: '+967', code: 'YE' },
];
